# ESP32-C6 WiFi 6 + Zigbee/Thread（variant: esp32c6）
substitutions:
  chip: c6

packages:
  base: !include common.yaml
  network: !include network.yaml

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
